### PR TITLE
Readme game instructions (Milestone 4)

### PR DESCRIPTION
**Pull request by mikethreels**
- updated readme file.

### CODE REVIEW

**Comment by uryelah** [comment]
Hi **Michael Threels & Hasan Kharouf**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with your README file, I loved how you've added a gif to show how the game is played!
There's just one improvement needed and you'll be free from this milestone. You got this! 💪 

# Required Changes 🏗️ 🐛 💡

- [x] Be more explicit about the how to start the game and what commands you need to enter in the terminal. I know you have the gif but it's always good to be as clear as one can be.
You can use the code markup so it's clear that `bundle i` for example is a command you should enter.
Don't assume the person reading your instructions is well versed on ruby or any command needed to download and play the game.

-----

 **Kindly fix the pointed out issues before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by WinterCore** [comment]
Hey @uryelah.
Thanks for the review.

> You can use the code markup so it's clear that bundle i for example is a command you should enter.

First of all, it's clearly stated in the `Playing the game` section in the readme that you should run `bundle install`
Second of all we're not even using any external Gems, so running `bundle install` is not required.

**Comment by uryelah** [comment]
I just pointed out the 'bundle i' because it was in your readme file
instructions ;-)

Em qui., 18 de jun. de 2020 às 13:20, WinterCore <notifications@github.com>
escreveu:

**Comment by WinterCore** [comment]
Hey @uryelah.

I read that wrong. I understand what you mean now.

Sorry about that.

**Comment by Dandush03** [comment]
# Status: 🟢 Project Approved 🟢 

### Great work following past reviews, good luck on your next assignment

happy coding

**Pull request merged**
